### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by adamchainz** [certifi/certifi.io#19]
I can't get certifi.io to load, it just times out.

**Comment by benoitc** [comment]
The instance running the process have been archived by error. I'm taking care of it. ETA: +2h

**Comment by benoitc** [comment]
fixed. sorry for the inconvenience.

**Comment by benoitc** [comment]
i've added to the status board there so the error shouldn't happen any more.

**Comment by adamchainz** [comment]
Btw I checked back, it was down on August 21 too and I emailed @Lukasa then but didn't get a reply. Presumably it has been back since.

**Comment by benoitc** [comment]
yes it was: https://github.com/certifi/certifi.io/issues/16#issuecomment-424646038  has been closed on 09/26.
