### ISSUE TITLE
certifi.io redirects to pip documentation

### ISSUE THREAD

**Issue by jlaine** [certifi/certifi.io#20]
I don't know whether it's intentional, but visiting https://certifi.io/ takes me to https://pip.pypa.io/en/stable/ and not to https://certifiio.readthedocs.io/en/latest/ ?

**Comment by benoitc** [comment]
certifi.io is supposed to redirect to cetifi.io on readthedocs. I didn't
changed myself the configuration on readsthedoc. I will check what happened.

**Comment by benoitc** [comment]
should be fixed now. I am waiting for the "www" propagation.  Waiting that I let the ticket open.

**Comment by benoitc** [comment]
done. thanks for the report

**Comment by jlaine** [comment]
Thank you @benoitc for the quick turnaround!
