### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by dtrodrigues** [certifi/certifi.io#23]
https://certifi.io is returning a 403 forbidden

**Comment by benoitc** [comment]
that's probably RTD that change again their conf or something like it. I will look at it, eventually move it to somewhere else.

**Comment by sigmavirus24** [comment]
@benoitc it looks like it's caused by cloudflare, not Read the Docs

**Comment by Lukasa** [comment]
I think it’s RTD configuration though; python-hyper.org is also affected, and it appears when accessing it directly via hyper-documentation.readthedocs.io. So something in the RTD config is leading to this outcome.

**Comment by christian-korneck** [comment]
it's been down > 2 weeks now? 🧐

**Comment by benoitc** [comment]
i will look at it.  I may reconsider my support o f it on the long term due to the lack of activity of this community.

**Comment by seizethedave** [comment]
I'd like to refer to the site, but it is still down.

**Comment by greenlaw110** [comment]
still down...

**Comment by benoitc** [comment]
Hrm should be online. i will look at it until tomorrow. I may just move everything to my own storage. The question is is this project still alive?

**Comment by kmulka-medigo** [comment]
Still down. I know that certifi is used by the requests library which is used by a lot of people.

**Comment by benoitc** [comment]
something changed in readthedoc. I will move the website elsewhere and update it a little. It will have to wait the week-end  as I have no time to look at it until then. Also no one bothered to answer to my question.

**Comment by tucked** [comment]
Down for over a year? 😬

**Comment by dtrodrigues** [comment]
https://certifi.io/ is working now
