### ISSUE TITLE
TLS on certifi.io

### ISSUE THREAD

**Issue by Lukasa** [certifi/certifi.io#4]
We should be serving certifi.io over TLS, to avoid being laughed at. =D

**Comment by benoitc** [comment]
bump

**Comment by Lukasa** [comment]
Mmm, I don't think I have access to the relevant machines. Will ping @kennethreitz and get him to give me credentials etc.

**Comment by benoitc** [comment]
cool :) Would be cool to connect to certifi.io using https...

**Comment by Lukasa** [comment]
Cool, so I should be aiming to do this tomorrow. Probably won't happen until Friday, but that should be fine.

**Comment by Lukasa** [comment]
That was wildly pessimistic. certifi.io now has HTTPS: I'm going to enable HSTS and add it to the preload list shortly.

**Comment by Lukasa** [comment]
Alright, HSTS is on as is a static 301 from HTTP to HTTPS. We're also in the HSTS preload queue. The cert is valid for three years, so that should be plenty of time!

**Comment by Lukasa** [comment]
Relevant: https://www.ssllabs.com/ssltest/analyze.html?d=certifi.io
