### ISSUE TITLE
erlang package of certifi

### ISSUE THREAD

**Issue by benoitc** [certifi/certifi.io#8]
Hi,

I just made a simple erlang application to package the CA bundle from certifi: https://github.com/benoitc/erlang-certfi

It will be used in hackney an Erlang http client library and the package using it. Maybe you can add a link to it or simply fork it here.

**Comment by Lukasa** [comment]
This is great @benoitc, thanks!

Are you happy to bring that repository under this organisation? If you are, we'd be delighted to have it. Otherwise, I'll just link from `certifi.io`.

**Comment by benoitc** [comment]
@Lukasa I am fine to have it in certifi.io, it will allow more people to see it.

**Comment by benoitc** [comment]
Let me know how to do the move, I will do ASAP :)

**Comment by Lukasa** [comment]
I've invited you to the Erlang team for this organisation: when you accept you *should* be able to transfer ownership of your repository from the 'Settings' section. Let me know if you can't. =)

**Comment by benoitc** [comment]
I tryed. It tell me that I don't have the admin right on certifi to do it :/

[image: Screen Shot 2015-09-10 at 15.38.13.png]

**Comment by Lukasa** [comment]
Hmm, try now?

**Comment by benoitc** [comment]
yes it worked. And done :)

Thanks!

**Comment by Lukasa** [comment]
Awesome, and the link to the erlang repository is available on `certifi.io`. Thanks @benoitc! :cake:

**Comment by benoitc** [comment]
pretty cool, thanks :)

**Comment by sigmavirus24** [comment]
We should probably publicize how to transfer repos to the org which would require one of the organization Owners being added as admin and being able to move the repository.

**Comment by benoitc** [comment]
:+1:
